export const TYPEMAP = {
  mysql: 'MySQL',
  oracle: 'Oracle',
  mongodb: 'MongoDB',
  elasticsearch: 'Elasticsearch',
  redis: 'Redis',
  postgres: 'PostgreSQL',
  sqlserver: 'SQL Server',
  'gbase-8s': 'GBase 8s',
  'sybase ase': 'Sybase ASE',
  gaussdb200: 'GaussDB200',
  db2: 'IBM Db2',
  mem_cache: 'Memory Cache',
  file: 'File(s)',
  custom_connection: 'Custom connection',
  'rest api': 'REST API',
  'dummy db': 'Dummy DB',
  gridfs: 'GridFS',
  kafka: 'Kafka',
  mariadb: 'MariaDB',
  'mysql pxc': 'MySQL PXC',
  jira: 'Jira',
  dameng: 'DM DB',
  hive: 'Hive',
  tcp_udp: 'TCP/IP',
  kudu: 'KUDU',
  hbase: 'HBase',
  mq: 'MQ',
  greenplum: 'Greenplum',
  tidb: 'TiDB',
  hana: 'SAP HANA',
  clickhouse: 'ClickHouse',
  adb_mysql: 'ADB MySQL',
  adb_postgres: 'ADB PostgreSQL',
  vika: 'Vika',
  kundb: 'KunDB',
  hazelcast_cloud_cluster: 'Hazelcast Cloud',
  aliyun_mariadb: 'Aliyun RDS for MariaDB',
  aliyun_mongodb: 'Aliyun MongoDB',
  aliyun_mysql: 'Aliyun RDS for MySQL',
  aliyun_postgres: 'Aliyun RDS for PG',
  aliyun_sqlserver: 'Aliyun RDS for SQLServer',
  tencent_mariadb: 'TencentDB for MariaDB',
  tencent_mongodb: 'TencentDB MongoDB',
  tencent_mysql: 'TencentDB for MySQL',
  tencent_postgres: 'TencentDB for PG',
  tencent_sqlserver: 'TencentDB for SQLServer'
}
