/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElIconCopyDocument: typeof import('@element-plus/icons-vue')['CopyDocument']
  const ElIconRefresh: typeof import('@element-plus/icons-vue')['Refresh']
  const ElIconSearch: typeof import('@element-plus/icons-vue')['Search']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
}
