/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElDropdown: typeof import('element-plus/es').ElDropdown
  const ElDropdownItem: typeof import('element-plus/es').ElDropdownItem
  const ElDropdownMenu: typeof import('element-plus/es').ElDropdownMenu
  const ElIconCopyDocument: typeof import('@element-plus/icons-vue').CopyDocument
  const ElInput: typeof import('element-plus/es').ElInput
  const ElMessage: typeof import('element-plus/es').ElMessage
  const ElMessageBox: typeof import('element-plus/es').ElMessageBox
  const ElSwitch: typeof import('element-plus/es').ElSwitch
  const IconMingcuteCheckCircleFill: typeof import('~icons/mingcute/check-circle-fill').default
  const IconMingcuteCloseCircleFill: typeof import('~icons/mingcute/close-circle-fill').default
  const IconMingcuteInformationFill: typeof import('~icons/mingcute/information-fill').default
  const IconMingcuteWarningFill: typeof import('~icons/mingcute/warning-fill').default
}
