/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./components/guide/Account.vue')['default']
    ConnectionTypeDialog: typeof import('./components/ConnectionTypeDialog.vue')['default']
    Datetime: typeof import('./components/filter-bar/Datetime.vue')['default']
    DatetimeRange: typeof import('./components/filter-bar/DatetimeRange.vue')['default']
    Deploy: typeof import('./components/guide/Deploy.vue')['default']
    DeploymentMethod: typeof import('./components/guide/DeploymentMethod.vue')['default']
    Details: typeof import('./components/guide/Details.vue')['default']
    Guide: typeof import('./components/guide/index.vue')['default']
    Header: typeof import('./components/the-header/Header.vue')['default']
    InlineInput: typeof import('./components/InlineInput.vue')['default']
    Main: typeof import('./components/filter-bar/Main.vue')['default']
    Pay: typeof import('./components/guide/Pay.vue')['default']
    PopInput: typeof import('./components/filter-bar/PopInput.vue')['default']
    Renew: typeof import('./components/Renew.vue')['default']
    ReplicationTour: typeof import('./components/ReplicationTour.vue')['default']
    RequestErrorMessage: typeof import('./components/RequestErrorMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scenes: typeof import('./components/guide/Scenes.vue')['default']
    Spec: typeof import('./components/guide/Spec.vue')['default']
    StatusTag: typeof import('./components/StatusTag.vue')['default']
    TableFilter: typeof import('./components/TableFilter.vue')['default']
    TaskAlarmTour: typeof import('./components/TaskAlarmTour.vue')['default']
    TheHeader: typeof import('./components/the-header/index.vue')['default']
    Unsubscribe: typeof import('./components/Unsubscribe.vue')['default']
    UploadFile: typeof import('./components/UploadFile.vue')['default']
    VerificationCode: typeof import('./components/VerificationCode.vue')['default']
  }
}
