module.exports = {
	DFS_TCM_PLATFORM: 'dfs',
	DFS_IGNORE_PERMISSION: true,
	DFS_TM_API_PRE_URL: '/tm',
	DFS_TCM_API_PRE_URL: process.env.VUE_APP_API_PATH,
	DFS_CREATE_DATAFLOW_BY_FORM: 1,
	SHOW_CLASSIFY: 0,
	HIDE_MENU: 0
	//
	// DFS_HIDE_FUNCTION_BUTTON: 1,
	// DFS_SUPPORT_DFS: 1,
	// DFS_HIDE_MENU: 1,
	// DFS_HIDE_TOPBAR: 1,
	// DFS_HIDE_TABLE_TITLE: 1,
	// DFS_HIDE_CONNECTION_OUTSIDE_PART: 1,
	// DFS_SHOW_THEME_CSS: 1,
	// DFS_HIDE_EXPORT: 1,
	// DFS_HIDE_IMPORT: 1,
	// DFS_HIDE_SCHEDULE: 1,
	// DFS_SHOW_REGION_AND_ZONE: 1,
	// DFS_SHOW_DATAFLOW_LOG: 1,
	// DFS_SHOW_DATAFLOW_SETTING: 1,
	// DFS_SHOW_DATAFLOW_LOG_CANCEL_BUTTON: 1,
	// DFS_HIDE_DATAFLOW_EDIT_BUTTON: 1,
	// DFS_SHOW_DATAFLOW_RELOADSCHEMA_BUTTON: 1,
	// DFS_SHOW_DATAFLOW_CELL_BUTTON: 1,
	// DFS_HIDE_HOT_KEY_BUTTON: 1,
	// DFS_HIDE_FOR_CLOUD: 1
}
